on:
  push:
    tags:
      - "v*.*.*"

name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: composer
      uses: docker://composer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: install --no-interaction --prefer-dist --optimize-autoloader
    - name: warm cache
      uses: phpDocumentor/phar-ga@latest
      with:
        args: php bin/console cache:warmup --env=prod
    - name: build phar
      uses: phpDocumentor/phar-ga@latest
      with:
        args: box compile
    - name: sign phar
      uses: phpDocumentor/phar-ga@latest
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      with:
        args: gpg --command-fd 0 --pinentry-mode loopback -u info@phpdoc.org --batch
          --detach-sign --output build/phpDocumentor.phar.asc build/phpDocumentor.phar
    - name: release phar
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/phpDocumentor.phar.asc
          build/phpDocumentor.phar
    - name: release shim
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Release
        repo: phpDocumentor/shim
        ref: '3.x'
        token: ${{ secrets.BOT_TOKEN }}
        inputs: '{ "tag": "${{ github.event.release.tag_name }}"}'

  release-docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Trigger
          uses: benc-uk/workflow-dispatch@v1
          with:
            workflow: Docker build
            token: ${{ secrets.BOT_TOKEN }}
